name: Merge request pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  checkstyle:

    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Run checkstyle w/ Gradle
        run: ./gradlew checkstyleMain

      - 
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/main.xml
  
  test:

    runs-on: macos-13

    needs: [checkstyle]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Run tests w/ Gradle
        run: ./gradlew clean test


  build:

    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17

    needs: [test]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4

      -
        name: Run build w/o tests
        run: ./gradlew build -x test

  docker:

    runs-on: ubuntu-latest
    
    needs: [build]
    steps:
        - 
          name: Checkout the code from main branch
          uses: actions/checkout@v4

        - 
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.9.0

        - 
          name: Build and push Docker images
          uses: docker/build-push-action@v6.13.0
          with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/mr:${{ github.sha }}