name: Create and push docker image to Docker Hub on "push" event.

on:
  push:
    branches: [ main ]
    
jobs:

  docker:
        
    runs-on: ubuntu-latest

    steps:
        - 
          name: Checkout the code from main branch
          uses: actions/checkout@v4

        - 
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.9.0

        - 
          name: Build and push Docker images
          uses: docker/build-push-action@v6.13.0
          with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/main:action
        
